const assert = require('assert');
const fs = require('fs');

const permission = fs.readFileSync('miniapp/src/utils/permission.ts', 'utf-8');
const api = fs.readFileSync('miniapp/src/utils/api.ts', 'utf-8');
const cloudRelayRoute = fs.readFileSync('gateway/src/routes/cloudRelay.js', 'utf-8');
const gatewayApp = fs.readFileSync('gateway/src/app.js', 'utf-8');
const miniappHome = fs.readFileSync('miniapp/src/pages/index/index.tsx', 'utf-8');
const appConfig = fs.readFileSync('miniapp/src/app.config.ts', 'utf-8');
const questionBankPage = fs.readFileSync('miniapp/src/pages/question-bank/index.tsx', 'utf-8');
const assetsPage = fs.readFileSync('miniapp/src/pages/assets/index.tsx', 'utf-8');
const loginPage = fs.readFileSync('miniapp/src/pages/login/index.tsx', 'utf-8');
const adminUsersPage = fs.readFileSync('miniapp/src/pages/admin/users/index.tsx', 'utf-8');
const studentsPage = fs.readFileSync('miniapp/src/pages/students/index.tsx', 'utf-8');
const teachersPage = fs.readFileSync('miniapp/src/pages/teachers/index.tsx', 'utf-8');
const paymentsPage = fs.readFileSync('miniapp/src/pages/payments/index.tsx', 'utf-8');
const schedulePage = fs.readFileSync('miniapp/src/pages/schedule/index.tsx', 'utf-8');
const scheduleDetailPage = fs.readFileSync('miniapp/src/pages/schedule/detail/index.tsx', 'utf-8');

assert.ok(permission.includes('readonlyModules'), 'miniapp permission should define readonlyModules');
assert.ok(permission.includes('allowedWriteTasks'), 'miniapp permission should define allowedWriteTasks');
assert.ok(permission.includes('studentModules'), 'miniapp permission should define studentModules');
assert.ok(permission.includes('getMiniappRolePolicy'), 'miniapp permission should expose role-specific policy');
assert.ok(permission.includes('isStudentUser'), 'miniapp permission should distinguish student users');
assert.ok(permission.includes('getLinkedStudentIds'), 'miniapp permission should expose linked student ids');
assert.ok(api.includes('createMiniappTask'), 'miniapp API should create allowed cloud tasks');
assert.ok(api.includes('readCloudSnapshot'), 'miniapp API should read cloud snapshots');
assert.ok(cloudRelayRoute.includes('filterSnapshotForUser'), 'cloud relay should filter snapshots by user role');
assert.ok(cloudRelayRoute.includes('isStudentUser'), 'cloud relay should distinguish student users');
assert.ok(cloudRelayRoute.includes('student_pricings'), 'student snapshot filter should use course/schedule student links');
assert.ok(gatewayApp.includes("app.use('/api/cloud', optionalAuth, cloudRelayRouter)"), 'gateway should mount cloud relay with optional auth on its own line');
assert.ok(miniappHome.includes('getMiniappRolePolicy'), 'home page should use role-specific policy');
assert.ok(!permission.includes("'teaching-tools'"), 'miniapp permission should not expose removed teaching tools module');
assert.ok(!miniappHome.includes("'teaching-tools'"), 'home page should not expose removed teaching tools module');
assert.ok(!appConfig.includes("'pages/tools/index'"), 'app config should not register removed teaching tools page');
assert.ok(!loginPage.includes('教学工具') && !loginPage.includes('teaching-tools'), 'login page should not mention removed teaching tools module');
assert.ok(!adminUsersPage.includes('teaching-tools') && !adminUsersPage.includes('教学工具'), 'admin user permissions should not mention removed teaching tools module');
assert.ok(!assetsPage.includes('提交任务') && !assetsPage.includes('主机处理') && !assetsPage.includes('本地数据主机'), 'asset page should not expose implementation wording');
assert.ok(!miniappHome.includes('student-dashboard-scope'), 'home page should not show explanatory student scope copy');
assert.ok(miniappHome.includes("user?.user_type !== 'student'"), 'home page should hide management shortcuts from students');
assert.ok(appConfig.includes("'pages/question-bank/index'"), 'app config should register the question bank page');
assert.ok(questionBankPage.includes('createMiniappTask'), 'question bank page should submit question bank operations');
assert.ok(questionBankPage.includes("'question-paper'"), 'question bank page should support paper assembly');
assert.ok(questionBankPage.includes("'paper-export-word'"), 'question bank page should support Word export');
assert.ok(questionBankPage.includes("'paper-export-pdf'"), 'question bank page should support PDF export');
assert.ok(questionBankPage.includes('getMiniappTaskResult'), 'question bank page should check paper/export task results');
assert.ok(questionBankPage.includes('lastTaskId'), 'question bank page should keep the last submitted task id');
assert.ok(questionBankPage.includes('resultFileUrl'), 'question bank page should keep downloadable result URLs');
assert.ok(questionBankPage.includes('Taro.downloadFile'), 'question bank page should download generated paper files');
assert.ok(!api.includes('studentApi') || !api.includes("create: (data: any) => api.post<any>('/scheduling/students'"), 'miniapp API must not expose direct student create');
assert.ok(!api.includes('studentApi') || !api.includes('update: (id: string, data: any) => api.put<any>(`/scheduling/students/${id}`'), 'miniapp API must not expose direct student update');
assert.ok(!api.includes('courseApi') || !api.includes("create: (data: any) => api.post<any>('/scheduling/courses'"), 'miniapp API must not expose direct course create');
assert.ok(!api.includes('scheduleApi') || !api.includes("create: (data: any) => api.post<any>('/scheduling/schedules'"), 'miniapp API must not expose direct schedule create');
assert.ok(!api.includes('paymentApi') || !api.includes("create: (data: any) => api.post<any>('/scheduling/payments'"), 'miniapp API must not expose direct payment create');
assert.ok(!api.includes('gradeApi') || !api.includes("create: (data: any) => api.post<any>('/scheduling/grades'"), 'miniapp API must not expose direct grade create');
assert.ok(!studentsPage.includes('withOfflineSupport') && !studentsPage.includes('addPendingChange'), 'students page should not queue core writes');
assert.ok(!teachersPage.includes('withOfflineSupport') && !teachersPage.includes('addPendingChange'), 'teachers page should not queue core writes');
assert.ok(!paymentsPage.includes('withOfflineSupport') && !paymentsPage.includes('addPendingChange'), 'payments page should not queue core writes');
assert.ok(!schedulePage.includes('/pages/schedule/edit/index'), 'schedule page should not expose edit entry');
assert.ok(!scheduleDetailPage.includes('addPendingChange') && !scheduleDetailPage.includes('updateLocalItem'), 'schedule detail should not update schedule status');

console.log('miniapp access policy checks passed');
