const assert = require('assert');
const {
  buildTeacherDetailsFromStudentDetails,
  filterStudentDetailsForRevenue,
} = require('./revenueDetailFilters');

const rows = [
  {
    key: 'mixed-self',
    scheduleId: 'schedule-mixed',
    studentId: 'student-self',
    studentName: '自有学生',
    teacherId: 'teacher-a',
    teacherName: '张老师',
    date: '2026-06-13',
    timeRange: '09:00-11:00',
    startTime: '2026-06-13 09:00',
    endTime: '2026-06-13 11:00',
    courseId: 'course-mixed',
    courseName: '混合班',
    courseType: 3,
    courseTypeName: '小组课',
    sourceType: 3,
    sourceTypeName: '混合班',
    institutionId: 'course-inst',
    durationHours: 2,
    billingUnit: 1,
    billingUnitName: '小时',
    tuitionUnitPrice: 150,
    tuitionTotal: 300,
    teacherFeeUnitPrice: 60,
    teacherFeeTotal: 120,
    teacherFeeMode: 2,
    teacherFeeModeName: '按学生',
    pricingSource: 'schedule',
  },
  {
    key: 'mixed-inst-a',
    scheduleId: 'schedule-mixed',
    studentId: 'student-inst-a',
    studentName: '机构A学生',
    teacherId: 'teacher-a',
    teacherName: '张老师',
    date: '2026-06-13',
    timeRange: '09:00-11:00',
    startTime: '2026-06-13 09:00',
    endTime: '2026-06-13 11:00',
    courseId: 'course-mixed',
    courseName: '混合班',
    courseType: 3,
    courseTypeName: '小组课',
    sourceType: 3,
    sourceTypeName: '混合班',
    institutionId: 'course-inst',
    durationHours: 2,
    billingUnit: 1,
    billingUnitName: '小时',
    tuitionUnitPrice: 200,
    tuitionTotal: 400,
    teacherFeeUnitPrice: 80,
    teacherFeeTotal: 160,
    teacherFeeMode: 2,
    teacherFeeModeName: '按学生',
    pricingSource: 'schedule',
  },
  {
    key: 'mixed-inst-b',
    scheduleId: 'schedule-mixed',
    studentId: 'student-inst-b',
    studentName: '机构B学生',
    teacherId: 'teacher-a',
    teacherName: '张老师',
    date: '2026-06-13',
    timeRange: '09:00-11:00',
    startTime: '2026-06-13 09:00',
    endTime: '2026-06-13 11:00',
    courseId: 'course-mixed',
    courseName: '混合班',
    courseType: 3,
    courseTypeName: '小组课',
    sourceType: 3,
    sourceTypeName: '混合班',
    institutionId: 'course-inst',
    durationHours: 2,
    billingUnit: 1,
    billingUnitName: '小时',
    tuitionUnitPrice: 220,
    tuitionTotal: 440,
    teacherFeeUnitPrice: 90,
    teacherFeeTotal: 180,
    teacherFeeMode: 2,
    teacherFeeModeName: '按学生',
    pricingSource: 'schedule',
  },
  {
    key: 'pure-inst-a',
    scheduleId: 'schedule-pure',
    studentId: '__institution_unbound__',
    studentName: '机构排课',
    teacherId: 'teacher-a',
    teacherName: '张老师',
    date: '2026-06-14',
    timeRange: '14:00-16:00',
    startTime: '2026-06-14 14:00',
    endTime: '2026-06-14 16:00',
    courseId: 'course-pure',
    courseName: '纯机构课',
    courseType: 4,
    courseTypeName: '大班课',
    sourceType: 2,
    sourceTypeName: '机构排课',
    institutionId: 'inst-a',
    durationHours: 2,
    billingUnit: 1,
    billingUnitName: '小时',
    tuitionUnitPrice: 250,
    tuitionTotal: 500,
    teacherFeeUnitPrice: 100,
    teacherFeeTotal: 200,
    teacherFeeMode: 1,
    teacherFeeModeName: '按课次',
    pricingSource: 'institution',
  },
];

const students = [
  { id: 'student-self', source_type: 1 },
  { id: 'student-inst-a', source_type: 2, institution_id: 'inst-a' },
  { id: 'student-inst-b', source_type: 2, institution_id: 'inst-b' },
];

const filtered = filterStudentDetailsForRevenue(rows, students, { institutionId: 'inst-a' });

assert.deepStrictEqual(filtered.map(row => row.key), ['mixed-inst-a', 'pure-inst-a']);
assert.strictEqual(filtered.reduce((sum, row) => sum + row.tuitionTotal, 0), 900);
assert.strictEqual(filtered.reduce((sum, row) => sum + row.teacherFeeTotal, 0), 360);

const teacherDetails = buildTeacherDetailsFromStudentDetails(filtered);
assert.strictEqual(teacherDetails.length, 2);
assert.deepStrictEqual(
  teacherDetails.map(row => ({
    scheduleId: row.scheduleId,
    studentNames: row.studentNames,
    studentCount: row.studentCount,
    durationHours: row.durationHours,
    teacherFeeTotal: row.teacherFeeTotal,
  })),
  [
    {
      scheduleId: 'schedule-mixed',
      studentNames: '机构A学生',
      studentCount: 1,
      durationHours: 2,
      teacherFeeTotal: 160,
    },
    {
      scheduleId: 'schedule-pure',
      studentNames: '机构排课',
      studentCount: 0,
      durationHours: 2,
      teacherFeeTotal: 200,
    },
  ]
);

console.log('revenueDetailFilters tests passed');
