export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/schedule/index',
    'pages/schedule/detail/index',
    'pages/schedule/edit/index',
    'pages/students/index',
    'pages/student-detail/index',
    'pages/courses/index',
    'pages/teachers/index',
    'pages/payments/index',
    'pages/stats/index',
    'pages/tools/index',
    'pages/tools/detail/index',
    'pages/assets/index',
    'pages/settings/index',
    'pages/admin/users/index',
    'pages/admin/invitations/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#1890ff',
    navigationBarTitleText: '教育综合服务平台',
    navigationBarTextStyle: 'white',
    backgroundColor: '#f5f5f5',
  },
  tabBar: {
    color: '#999',
    selectedColor: '#1890ff',
    backgroundColor: '#fff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/schedule/index',
        text: '课程表',
        iconPath: 'assets/tab-calendar.png',
        selectedIconPath: 'assets/tab-calendar-active.png',
      },
      {
        pagePath: 'pages/students/index',
        text: '学员',
        iconPath: 'assets/tab-students.png',
        selectedIconPath: 'assets/tab-students-active.png',
      },
      {
        pagePath: 'pages/settings/index',
        text: '设置',
        iconPath: 'assets/tab-settings.png',
        selectedIconPath: 'assets/tab-settings-active.png',
      },
    ],
  },
});
